-- $Id: armap.lua 3189 2008-11-12 09:09:23Z google frog $
unitDef = {
  unitname                      = "armap",
  name                          = "Aircraft Plant",
  description                   = "Produces Aircraft, Builds at 9 m/s",
  acceleration                  = 0,
  activateWhenBuilt             = false,
  bmcode                        = "0",
  brakeRate                     = 0,
  buildCostEnergy               = 700,
  buildCostMetal                = 700,
  builder                       = true,
  buildingGroundDecalDecaySpeed = 0.01,
  buildingGroundDecalSizeX      = 9,
  buildingGroundDecalSizeY      = 7,
  buildingGroundDecalType       = "asphalt512.dds",

  buildoptions                  = {
    "armca",
    "armpeep",
    "armfig",
    "armhawk",
    "armlance",
    "armthund",
    "armpnix",
    "armstiletto",
    "armcybr",
    "armawac",
  },

  buildPic                      = "ARMAP.png",
  buildTime                     = 700,
  canMove                       = true,
  canPatrol                     = true,
  canstop                       = "1",
  category                      = "UNARMED SINK",
  corpse                        = "DEAD",
  energyMake                    = 0.225,
  energyUse                     = 0,
  explodeAs                     = "LARGE_BUILDINGEX",
  footprintX                    = 8,
  footprintZ                    = 6,
  iconType                      = "facair",
  idleAutoHeal                  = 5,
  idleTime                      = 1800,
  isAirBase                     = true,
  mass                          = 350,
  maxDamage                     = 3500,
  maxSlope                      = 15,
  maxVelocity                   = 0,
  metalMake                     = 0.225,
  minCloakDistance              = 150,
  noAutoFire                    = false,
  objectName                    = "ARMAP",
  seismicSignature              = 4,
  selfDestructAs                = "LARGE_BUILDING",
  showNanoSpray                 = false,
  side                          = "ARM",
  sightDistance                 = 273,
  smoothAnim                    = true,
  TEDClass                      = "PLANT",
  turnRate                      = 0,
  useBuildingGroundDecal        = true,
  workerTime                    = 9,
  yardMap                       = "ooooooo ooooooo occccco occccco occccco occccco",

  featureDefs                   = {

    DEAD  = {
      description      = "Wreckage - Aircraft Plant",
      blocking         = true,
      category         = "corpses",
      damage           = 7000,
      energy           = 0,
      featureDead      = "DEAD2",
      featurereclamate = "SMUDGE01",
      footprintX       = 7,
      footprintZ       = 6,
      height           = "40",
      hitdensity       = "100",
      metal            = 420,
      object           = "ARMAP_DEAD",
      reclaimable      = true,
      reclaimTime      = 1680,
      seqnamereclamate = "TREE1RECLAMATE",
      world            = "All Worlds",
    },


    DEAD2 = {
      description      = "Debris - Aircraft Plant",
      blocking         = false,
      category         = "heaps",
      damage           = 7000,
      energy           = 0,
      featureDead      = "HEAP",
      featurereclamate = "SMUDGE01",
      footprintX       = 6,
      footprintZ       = 6,
      height           = "4",
      hitdensity       = "100",
      metal            = 420,
      object           = "6X6B",
      reclaimable      = true,
      reclaimTime      = 1680,
      seqnamereclamate = "TREE1RECLAMATE",
      world            = "All Worlds",
    },


    HEAP  = {
      description      = "Debris - Aircraft Plant",
      blocking         = false,
      category         = "heaps",
      damage           = 7000,
      energy           = 0,
      featurereclamate = "SMUDGE01",
      footprintX       = 6,
      footprintZ       = 6,
      height           = "4",
      hitdensity       = "100",
      metal            = 210,
      object           = "6X6B",
      reclaimable      = true,
      reclaimTime      = 840,
      seqnamereclamate = "TREE1RECLAMATE",
      world            = "All Worlds",
    },

  },

}

return lowerkeys({ armap = unitDef })
